on:
  push:
    branches:
      - main

jobs:
  build_push_image:
    runs-on: [self-hosted]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run build with make
        run: make build-k8s

      - name: Tag image
        run: make tag-k8s

      - name: Push image
        run: make push-k8s

      - name: Restart kubernetes deployment
        run: kubectl -n infocare-web rollout restart deployment web-deployment
